### ISSUE TITLE
mount dir change permission

### ISSUE THREAD

**Issue by dipenpatel235** [davidknoll/mongofuse#2]
hello i want to change permission instead of root user.
so how can i do that ?

**Comment by davidknoll** [comment]
If you are mounting a new mongofuse filesystem, ie. the database containing the directory doesn't yet exist, the root of the filesystem (what you'll see as the mount directory) will be owned by the user you're running mongofuse as.

If you want to allow other users to access a mongofuse filesystem (and the same goes for other FUSE filesystems), you may want to look at the `allow_other` and `allow_root` mount options.

`chmod`, `chown` and `chgrp` work in pretty much the usual way. You can't `chmod`, `chown` or `chgrp` unless you are the file/directory's existing owner (or root with the `allow_root` option). You can't `chown` to a user other than yourself, unless you are root (using the `allow_root` option), and you can't `chgrp` to a group you are not a member of, unless you are root (using the `allow_root` option).

You may also want to look at the `default_permissions` mount option if you want directory permissions properly enforced.

Sorry for the delay, I hope this helps.
